version: "3.9"

services:
  db:
    image: postgres:15
    container_name: hospital_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/data:/docker-entrypoint-initdb.d/data
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
