--query 17
SELECT DISTINCT p.*
FROM PATIENTS p
INNER JOIN ADMISSIONS a ON p.SUBJECT_ID = a.SUBJECT_ID
INNER JOIN NOTEEVENTS n ON a.HADM_ID = n.HADM_ID
WHERE n.CATEGORY = 'Radiology'
AND (n.TEXT LIKE '%chest%' OR n.TEXT LIKE '%Chest%' OR n.TEXT LIKE '%CHEST%');
