--query 20
SELECT 
    p.SUBJECT_ID,
    p.GENDER,
    p.DOB,
    COUNT(DISTINCT a.HADM_ID) AS total_admissions,
    COUNT(DISTINCT i.ICUSTAY_ID) AS total_icu_stays,
    COUNT(d.SEQ_NUM) AS total_diagnoses
FROM PATIENTS p
LEFT JOIN ADMISSIONS a ON p.SUBJECT_ID = a.SUBJECT_ID
LEFT JOIN ICUSTAYS i ON a.HADM_ID = i.HADM_ID
LEFT JOIN DIAGNOSES_ICD d ON a.HADM_ID = d.HADM_ID
WHERE p.SUBJECT_ID = 10104
GROUP BY p.SUBJECT_ID, p.GENDER, p.DOB;